# Generated by Django 6.0.5 on 2026-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('payment_due', 'Nhắc thanh toán'), ('payment_success', 'Thanh toán thành công'), ('payment_rejected', 'Thanh toán bị từ chối'), ('new_invoice', 'Hóa đơn mới'), ('contract', 'Hợp đồng'), ('system', 'Thông báo hệ thống')], default='system', max_length=20),
        ),
    ]
