# Generated by Django 6.0.5 on 2026-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_owner_alter_roomtenant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtenant',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
