# Generated by Django 6.0.5 on 2026-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomtenant_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtenant',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
    ]
