# Generated by Django 6.0.5 on 2026-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_floor_capacity_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtenant',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
