# Generated by Django 6.0.5 on 2026-06-12 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0004_roomtenant_duration_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('room_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('old_electric', models.IntegerField()),
                ('new_electric', models.IntegerField()),
                ('old_water', models.IntegerField()),
                ('new_water', models.IntegerField()),
                ('service_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('electricity_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('water_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_electric', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_water', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_price', models.DecimalField(decimal_places=0, default=3500, max_digits=10)),
                ('water_price', models.DecimalField(decimal_places=0, default=15000, max_digits=10)),
                ('common_service_fee', models.DecimalField(decimal_places=0, default=100000, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_price', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
