# Generated by Django 6.0.5 on 2026-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='new_electric',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='new_water',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='old_electric',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='old_water',
        ),
        migrations.AddField(
            model_name='invoice',
            name='electricity_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='water_usage',
            field=models.IntegerField(default=0),
        ),
    ]
