# Generated by Django 4.2.30 on 2026-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_bankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('none', 'Chưa nộp'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='none', max_length=10),
        ),
    ]
